version: '3.9'

services:

  jenkins-docker:
    image: docker:dind
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - .datos/certs:/certs/client
      - .datos/jenkins:/var/jenkins_home
    ports:
      - 2376:2376
    networks: 
      - jenkins
    privileged: true

  jenkins:
    build: .
    image: myjenkins-blueocean:1.1
    container_name: jenkyns-blueocean
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    volumes:
      - .datos/jenkins:/var/jenkins_home
      - .datos/jenkins:/certs/client:ro
    ports:
      - 8081:8080
      - 50000:50000
    networks:
      - jenkins

networks:
  jenkins:


